---

- name: "Kubectl on local machine"
  hosts: '*'
  user: sebastian
  become: true

  vars: 
    username: w
  
  tasks: 
    - name: "czy plik istnieje // checking if file admin.conf exists"
      file: 
        path: /etc/kubernetes/admin.conf
        state: file

    - name: "pobierz plik admin.conf // copying admin.conf from remote host to local machine to .kube/config"
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{username}}/.kube/config"
        flat: yes
