---

- name: master1
  hosts: '*'
  vars: 
    user: marian
    password: "marian"
  become: true

  tasks: 

    - name: "tworzy uzytkownika i dodaje do grupy // creating user and adding to groups"
      user:
        name: "{{ user }}"
        password: "{{ password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        groups: root, sudo
    
    - name: "sprawdza czy istnieje katalog .ssh/ // check if .ssh/ dir exists"
      stat: 
        path: "/home/{{user}}/.ssh/"
      register: ssh

    - name: "tworze katalog .ssh/ // creating .ssh/ dir if don't exist"
      file:
        path: "/home/{{user}}/.ssh/"
        state: directory
      when: ssh.stat.exists == false

    - name: "sprawdza czy istnieje plik .pub // checking if .pub file exists"
      stat: 
        path: "/home/{{user}}/rsa_key_{{user}}.pub"
      register: pub

    - name: "tworze klucz ssh .pub // creating ssh key"
      command: "ssh-keygen -q -t rsa -f /home/{{user}}/rsa_key_{{users}} -C {{ user }} -N '' "
      when: pub.stat.exists == false

    - name: "kopiuje zawartosc pliku .pub do pliku authorized_keys // copy .pub file from home, and changing it name to authorized_keys in .ssh directory"
      shell: "cp /home/{{user}}/rsa_key_{{user}}.pub /home/{{user}}/.ssh/authorized_keys"
      
    - name: "nadaje prawa plikom w home/ // gives permissions to home directory"
      file: path="/home/{{user}}/"" owner="{{user}}" group="{{user}}" state=directory recurse=yes
