---

- name: master1
  hosts: '*'
  vars: 
    user: marian
    password: "marian"
  user: sebastian
  become: true

  tasks: 

    - name: "tworzy uzytkownika i dodaje do grupy [vm_master1]"
      user:
        name: "{{ user }}"
        password: "{{ password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        groups: root, sudo
    
    - name: "sprawdza czy istnieje katalog .ssh/"
      stat: 
        path: /home/marian/.ssh/
      register: ssh

    - name: "tworze katalog .ssh/"
      file:
        path: /home/marian/.ssh/
        state: directory
      when: ssh.stat.exists == false

    - name: "sprawdza czy istnieje plik .pub"
      stat: 
        path: /home/marian/rsa_key_marian.pub
      register: pub

    - name: "tworze klucz ssh .pub"
      command: ssh-keygen -q -t rsa -f /home/marian/rsa_key_marian -C "{{ user }}" -N ""
      when: pub.stat.exists == false

    - name: "kopiuje zawartosc pliku .pub do pliku authorized_keys"
      shell: "cp /home/marian/rsa_key_marian.pub /home/marian/.ssh/authorized_keys"
      
    - name: "nadaje prawa plikom w home/marian uzytkownikowi marian"
      file: path=/home/marian/ owner=marian group=marian state=directory recurse=yes
